apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cartsdb-svc-run
spec:
  serviceAccountName: sa
  taskRef:
    name: cartsdb-svc
  params:
    - name: action
      value: apply
    - name: output
      value: |
        - name: job-name
          valueFrom: '{.metadata.name}'
        - name: job-namespace
          valueFrom: '{.metadata.namespace}'
#    - name: set-ownerreference
#      value: "false"
    - name: manifest
      value: |
        apiVersion: v1
        kind: Service
        metadata:
          name: carts-db
        spec:
          ports:
          - port: 27017
            targetPort: 27017
          selector:
            app: carts-db
