apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
spec:
  type: NodePort
  selector:
    app: orders
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
