apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: orders-pipelinerun
spec:
  pipelineRef:
    name: orders-pipeline
  serviceAccountName: sa
  resources:
  - name: level3-project
    resourceSpec:
      type: git
      params:
      - name: revision
        value: main
      - name: url
        value: https://github.com/Ra-tnt/level3-project
  params:
    - name: imagename 
      value: "raghadq/orders"
    - name: outputfile
      value: |
        - name: job-name
          valueFrom: '{.metadata.name}'
        - name: job-namespace
          valueFrom: '{.metadata.namespace}'
    - name: manifestfile
      value: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: orders
          labels:
            app: orders
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: orders
          template:
            metadata:
              labels:
                app: orders
            spec:
              containers:
              - name: orders
                image: raghadq/orders
                resources:
                  limits:
                    cpu: 500m
                    memory: 500Mi
                  requests:
                    cpu: 200m
                    memory: 500Mi
                ports:
                - containerPort: 80
    - name: manifestfilesvc
      value: |
        apiVersion: v1
        kind: Service
        metadata:
          name: orders
          labels:
            app: orders
        spec:
          type: NodePort
          selector:
            app: orders
          ports:
          - port: 80
            targetPort: 80
    - name: manifestfiledb
      value: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: orders-db
          labels:
            app: orders-db
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: orders-db
          template:
            metadata:
              labels:
                app: orders-db
            spec:
              containers:
              - name: orders-db
                image: mongo
                ports:
                - name: mongo
                  containerPort: 27017
    - name: manifestfiledbsvc
      value: |
        apiVersion: v1
        kind: Service
        metadata:
          name: orders-db
          labels:
            app: orders-db
        spec:
          ports:
          - port: 27017
            targetPort: 27017
          selector:
            app: orders-db

