apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: imagename
      default: "raghadq/orders:testing"
    - name: dockerfilepath
      default: /workspace/level3-project/orders/Dockerfile
    - name: contextpath
      default: /workspace/level3-project/orders
    - name: extraargsvalue
      default: ""
    - name: builderimage
      default: gcr.io/kaniko-project/executor:latest
    - name: kubeaction
      default: apply
    - name: manifestfile
      default:
    - name: outputfile
      default: "" 
    - name: manifestfilesvc
      default:
    - name: manifestfiledb
      default:
    - name: manifestfiledbsvc
      default:  
  tasks:
    - name: build-docker-orders
      taskRef:
        name: build-push-orders
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.imagename)"
      - name: DOCKERFILE
        value: "$(params.dockerfilepath)"
      - name: CONTEXT
        value: "$(params.contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-db-shipping
      taskRef:
        name: ordersdb-deploy
      runAfter: 
        - build-docker-orders
      params: 
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfiledb)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-db-shipping
      taskRef:
        name: ordersdb-svc
      runAfter:
        - deploy-pods-db-shipping
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfiledbsvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-pods-orders
      taskRef:
        name: orders-deploy
      runAfter: 
        - deploy-service-db-shipping
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service
      taskRef: 
        name: orders-svc
      runAfter:
        - deploy-pods-orders
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
      
  results:
    - name: imagedigest
      description: result of image digest
      value: $(tasks.build-docker-orders.results.IMAGE-DIGEST)


