apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: microservicedemo-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: shipping-imagename
      default: "raghadq/shipping:testing"
    - name: shipping-dockerfilepath
      default: /workspace/level3-project/shipping/Dockerfile
    - name: shipping-contextpath
      default: /workspace/level3-project/shipping
    - name: extraargsvalue
      default: ""
    - name: builderimage
      default: gcr.io/kaniko-project/executor:latest
    - name: kubeaction
      default: apply
    - name: outputfile
      default: "" 
    - name: shipping-manifestfile
      default:
    - name: shipping-manifestfilesvc
      default:

    - name: carts-imagename
      default: "raghadq/carts:testing"
    - name: carts-dockerfilepath
      default: /workspace/level3-project/carts/Dockerfile
    - name: carts-contextpath
      default: /workspace/level3-project/carts
    - name: carts-manifestfile
      default:
    - name: carts-manifestfilesvc
      default:
    - name: carts-manifestfiledb
      default:
    - name: carts-manifestfiledbsvc

    - name: orders-imagename
      default: "raghadq/orders"
    - name: orders-dockerfilepath
      default: /workspace/level3-project/orders/Dockerfile
    - name: orders-contextpath
      default: /workspace/level3-project/orders
    - name: orders-manifestfile
      default:
    - name: orders-manifestfilesvc
      default:
    - name: orders-manifestfiledb
      default:
    - name: orders-manifestfiledbsvc
      default:

    - name: payment-imagename
      default: "raghadq/payment"
    - name: payment-dockerfilepath
      default: /workspace/level3-project/payment/Dockerfile
    - name: payment-contextpath
      default: /workspace/level3-project/payment
    - name: payment-manifestfile
      default:
    - name: payment-manifestfilesvc
      default:

    - name: catalogue-imagename
      default: "raghadq/catalogue"
    - name: catalogue-dockerfilepath
      default: /workspace/level3-project/catalogue/Dockerfile
    - name: catalogue-contextpath
      default: /workspace/level3-project/catalogue
    - name: catalogue-imagenamedb
      default: "raghadq/catalogue-db"
    - name: catalogue-dockerfilepathdb
      default: /workspace/level3-project/catalogue/catalogue-db/Dockerfile
    - name: catalogue-contextpathdb
      default: /workspace/level3-project/catalogue/catalogue-db
    - name: catalogue-manifestfile
      default:
    - name: catalogue-manifestfilesvc
      default:
    - name: catalogue-manifestfiledb
      default:
    - name: catalogue-manifestfiledbsvc
      default:
   
    - name: user-imagename
      default: "raghadq/user"
    - name: user-dockerfilepath
      default: /workspace/level3-project/user/Dockerfile
    - name: user-contextpath
      default: /workspace/level3-project/user
    - name: user-imagenamedb
      default: "raghadq/user-db"
    - name: user-dockerfilepathdb
      default: /workspace/level3-project/user/user-db/Dockerfile
    - name: user-contextpathdb
      default: /workspace/level3-project/user/user-db
    - name: user-manifestfile
      default:
    - name: user-manifestfilesvc
      default:
    - name: user-manifestfiledb
      default:
    - name: user-manifestfiledbsvc
      default:

    - name: frontend-imagename
      default: "raghadq/frontend"
    - name: frontend-dockerfilepath
      default: /workspace/level3-project/front-end/Dockerfile
    - name: frontend-contextpath
      default: /workspace/level3-project/front-end
    - name: frontend-manifestfile
      default:
    - name: frontend-manifestfilesvc
      default:
    - name: manifestfileingress
      default:

  tasks:
    - name: build-docker-shipping
      taskRef:
        name: build-push-shipping
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.shipping-imagename)"
      - name: DOCKERFILE
        value: "$(params.shipping-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.shipping-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-shipping
      taskRef:
        name: shipping-deploy
      runAfter: 
        - build-docker-shipping
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.shipping-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-shipping
      taskRef: 
        name: shipping-svc
      runAfter:
        - deploy-pods-shipping
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.shipping-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: build-docker-carts
      taskRef:
        name: build-push-carts
      runAfter:
        - deploy-service-shipping
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.carts-imagename)"
      - name: DOCKERFILE
        value: "$(params.carts-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.carts-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-db-carts
      taskRef:
        name: cartsdb-deploy
      runAfter:
        - build-docker-carts
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.carts-manifestfiledb)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-db-carts
      taskRef:
        name: cartsdb-svc
      runAfter:
        - deploy-pods-db-carts
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.carts-manifestfiledbsvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-pods-carts
      taskRef:
        name: carts-deploy
      runAfter:
        - deploy-service-db-carts
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.carts-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-carts
      taskRef:
        name: carts-svc
      runAfter:
        - deploy-pods-carts
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.carts-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: build-docker-orders
      taskRef:
        name: build-push-orders
      runAfter:
        - deploy-service-carts
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.orders-imagename)"
      - name: DOCKERFILE
        value: "$(params.orders-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.orders-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-db-orders
      taskRef:
        name: ordersdb-deploy
      runAfter:
        - build-docker-orders
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.orders-manifestfiledb)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-db-orders
      taskRef:
        name: ordersdb-svc
      runAfter:
        - deploy-pods-db-orders
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.orders-manifestfiledbsvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-pods-orders
      taskRef:
        name: orders-deploy
      runAfter:
        - deploy-service-db-orders
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.orders-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-orders
      taskRef:
        name: orders-svc
      runAfter:
        - deploy-pods-orders
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.orders-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: build-docker-payment
      taskRef:
        name: build-push-payment
      runAfter:
        - deploy-service-orders
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.payment-imagename)"
      - name: DOCKERFILE
        value: "$(params.payment-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.payment-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-payment
      taskRef:
        name: payment-deploy
      runAfter: 
        - build-docker-payment
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.payment-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-payment
      taskRef: 
        name: payment-svc
      runAfter:
        - deploy-pods-payment
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.payment-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: build-docker-catalogue
      taskRef:
        name: build-push-catalogue
      runAfter:
        - deploy-service-payment 
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.catalogue-imagename)"
      - name: DOCKERFILE
        value: "$(params.catalogue-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.catalogue-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: build-docker-cataloguedb
      taskRef:
        name: build-push-cataloguedb
      runAfter:
        - deploy-service-payment
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.catalogue-imagenamedb)"
      - name: DOCKERFILE
        value: "$(params.catalogue-dockerfilepathdb)"
      - name: CONTEXT
        value: "$(params.catalogue-contextpathdb)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-db-catalogue
      taskRef:
        name: cataloguedb-deploy
      runAfter:
        - build-docker-cataloguedb
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.catalogue-manifestfiledb)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-db-catalogue
      taskRef:
        name: cataloguedb-svc
      runAfter:
        - deploy-pods-db-catalogue
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.catalogue-manifestfiledbsvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-pods-catalogue
      taskRef:
        name: catalogue-deploy
      runAfter:
        - build-docker-catalogue
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.catalogue-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-catalogue
      taskRef:
        name: catalogue-svc
      runAfter:
        - deploy-pods-catalogue
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.catalogue-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: build-docker-userdb
      taskRef:
        name: build-push-userdb
      runAfter:
        - deploy-service-catalogue
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.user-imagenamedb)"
      - name: DOCKERFILE
        value: "$(params.user-dockerfilepathdb)"
      - name: CONTEXT
        value: "$(params.user-contextpathdb)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: build-docker-user
      taskRef:
        name: build-push-user
      runAfter:
        - deploy-service-catalogue
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.user-imagename)"
      - name: DOCKERFILE
        value: "$(params.user-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.user-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-db-user
      taskRef:
        name: userdb-deploy
      runAfter:
        - build-docker-user
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.user-manifestfiledb)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-db-user
      taskRef:
        name: userdb-svc
      runAfter:
        - deploy-pods-db-user
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.user-manifestfiledbsvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-pods-user
      taskRef:
        name: user-deploy
      runAfter:
        - deploy-service-db-user
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.user-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-user
      taskRef:
        name: user-svc
      runAfter:
        - deploy-pods-user
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.user-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: build-docker-frontend
      taskRef:
        name: build-push-frontend
      runAfter:
        - deploy-service-user 
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.frontend-imagename)"
      - name: DOCKERFILE
        value: "$(params.frontend-dockerfilepath)"
      - name: CONTEXT
        value: "$(params.frontend-contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-frontend
      taskRef:
        name: frontend-deploy
      runAfter:
        - build-docker-frontend
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.frontend-manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-frontend
      taskRef:
        name: frontend-svc
      runAfter:
        - deploy-pods-frontend
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.frontend-manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-ingress
      taskRef:
        name: frontend-ingress
      runAfter:
        - deploy-service-frontend
      params: 
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfileingress)"
      - name: output
        value: "$(params.outputfile)"

  results:
    - name: shipping-imagedigest
      description: result of image digest
      value: $(tasks.build-docker-shipping.results.IMAGE-DIGEST)
    - name: carts--imagedigest
      description: result of image digest
      value: $(tasks.build-docker-carts.results.IMAGE-DIGEST)
    - name: orders-imagedigest
      description: result of image digest
      value: $(tasks.build-docker-orders.results.IMAGE-DIGEST)
    - name: payment-imagedigest
      description: result of image digest 
      value: $(tasks.build-docker-payment.results.IMAGE-DIGEST)
    - name: catalogue-imagedigest
      description: result of image digest
      value: $(tasks.build-docker-catalogue.results.IMAGE-DIGEST)
    - name: catalogue-imagedigestdb
      description: result of image digest db
      value: $(tasks.build-docker-cataloguedb.results.IMAGE-DIGEST)
    - name: user-imagedigestdb
      description: result of image digest db
      value: $(tasks.build-docker-userdb.results.IMAGE-DIGEST)      
    - name: user-imagedigest
      description: result of image digest
      value: $(tasks.build-docker-user.results.IMAGE-DIGEST)
    - name: frontend-imagedigest
      description: result of image digest
      value: $(tasks.build-docker-frontend.results.IMAGE-DIGEST)
