#spec.template.metadata.labels: Invalid value: map[string]string{"app":"shipping"}: `selector` does not match template `labels`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: cicd
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: raghadq/shipping:testing
        ports:
        - containerPort: 80
        #securityContext:
        #  runAsNonRoot: true
        #  runAsUser: 10001
        #  capabilities:
        #    drop:
        #      - all
        #    add:
        #      - NET_BIND_SERVICE
        #  readOnlyRootFilesystem: true
       # volumeMounts:
       # - mountPath: /tmp
       #   name: tmp-volume
       # livenessProbe:
       #   httpGet:
       #     path: /health
       #     port: 80
       #   initialDelaySeconds: 300
       #   periodSeconds: 3
       # readinessProbe:
       #   httpGet:
       #     path: /health
       #     port: 80
       #   initialDelaySeconds: 180
       #   periodSeconds: 3
      #volumes:
      #  - name: tmp-volume
      #    emptyDir:
      #      medium: Memory
      #nodeSelector:
      #  beta.kubernetes.io/os: linux
