apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cartsdb-deploy-run
spec:
  serviceAccountName: sa
  taskRef:
    name: cartsdb-deploy
  params:
    - name: action
      value: apply
    - name: output
      value: |
        - name: job-name
          valueFrom: '{.metadata.name}'
        - name: job-namespace
          valueFrom: '{.metadata.namespace}'
#    - name: set-ownerreference
#      value: "false"
    - name: manifest
      value: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: carts-db
          labels:
            app: carts-db
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: carts-db
          template:
            metadata:
              labels:
                app: carts-db
            spec:
              containers:
              - name: carts-db
                image: mongo
                ports:
                - name: mongo
                  containerPort: 27017

