apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-test
spec:
  resources:
    inputs:
    - name: level3-project
      type: git
  params:
    - name: IMAGE
      description: name of the image
  steps:
    - name: apply-test
      image: "$(inputs.params.IMAGE)"
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/e2e-test/runner.sh"

