apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    name: carts
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: carts
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
