apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-push-run
spec:
  serviceAccountName: raghad-dockerhub
  taskRef:
    name: build-push
  params:
    - name: pathToDockerFile
      value: carts/Dockerfile
    - name: pathToContext
      value: /carts
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: source
    outputs:
      - name: builtImage
        resourceRef:
          name: result
