apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipelinerun
spec:
  pipelineRef:
    name: test-pipeline
  serviceAccountName: sa
  resources:
  - name: level3-project
    resourceSpec:
      type: git
      params:
      - name: revision
        value: main
      - name: url
        value: https://github.com/Ra-tnt/level3-project

