apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    name: shipping
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: shipping
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
