apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalogue-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: imagename
      default: "raghadq/catalogue"
    - name: dockerfilepath
      default: /workspace/level3-project/catalogue/Dockerfile
    - name: contextpath
      default: /workspace/level3-project/catalogue
    - name: imagenamedb
      default: "raghadq/catalogue-db"
    - name: dockerfilepathdb
      default: /workspace/level3-project/catalogue/catalogue-db/Dockerfile
    - name: contextpathdb
      default: /workspace/level3-project/catalogue/catalogue-db
    - name: extraargsvalue
      default: ""
    - name: builderimage
      default: gcr.io/kaniko-project/executor:latest
    - name: kubeaction
      default: apply
    - name: manifestfile
      default:
    - name: outputfile
      default: "" 
    - name: manifestfilesvc
      default:
    - name: manifestfiledb
      default:
    - name: manifestfiledbsvc
      default:  
  tasks:
    - name: build-docker-catalogue
      taskRef:
        name: build-push-catalogue
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.imagename)"
      - name: DOCKERFILE
        value: "$(params.dockerfilepath)"
      - name: CONTEXT
        value: "$(params.contextpath)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: build-docker-cataloguedb
      taskRef:
        name: build-push-cataloguedb
      resources:
        inputs:
          - name: level3-project
            resource: level3-project
      params:
      - name: IMAGE
        value: "$(params.imagenamedb)"
      - name: DOCKERFILE
        value: "$(params.dockerfilepathdb)"
      - name: CONTEXT
        value: "$(params.contextpathdb)"
      - name: EXTRA_ARGS
        value: "$(params.extraargsvalue)"
      - name: BUILDER_IMAGE
        value: "$(params.builderimage)"
    - name: deploy-pods-db-catalogue
      taskRef:
        name: cataloguedb-deploy
      runAfter: 
        - build-docker-cataloguedb
      params: 
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfiledb)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-db-catalogue
      taskRef:
        name: cataloguedb-svc
      runAfter:
        - deploy-pods-db-catalogue
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfiledbsvc)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-pods-catalogue
      taskRef:
        name: catalogue-deploy
      runAfter: 
        - deploy-service-db-catalogue
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfile)"
      - name: output
        value: "$(params.outputfile)"
    - name: deploy-service-catalogue
      taskRef: 
        name: catalogue-svc
      runAfter:
        - deploy-pods-catalogue
      params:
      - name: action
        value: "$(params.kubeaction)"
      - name: manifest
        value: "$(params.manifestfilesvc)"
      - name: output
        value: "$(params.outputfile)"
      
  results:
    - name: imagedigest
      description: result of image digest
      value: $(tasks.build-docker-catalogue.results.IMAGE-DIGEST)
