apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: user-pipelinerun
spec:
  pipelineRef:
    name: user-pipeline
  serviceAccountName: sa
  resources:
  - name: level3-project
    resourceSpec:
      type: git
      params:
      - name: revision
        value: main
      - name: url
        value: https://github.com/Ra-tnt/level3-project
  params:
    - name: imagename 
      value: "raghadq/user"
    - name: imagenamedb 
      value: "raghadq/user-db"
    - name: outputfile
      value: |
        - name: job-name
          valueFrom: '{.metadata.name}'
        - name: job-namespace
          valueFrom: '{.metadata.namespace}'
    - name: manifestfile
      value: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: user
          labels:
            app: user
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: user
          template:
            metadata:
              labels:
                app: user
            spec:
              containers:
              - name: user
                image: raghadq/user
                resources:
                  limits:
                    cpu: 300m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
                ports:
                - containerPort: 80
                env:
                - name: mongo
                  value: user-db:27017
    - name: manifestfilesvc
      value: |
        apiVersion: v1
        kind: Service
        metadata:
          name: user
          labels:
            app: user
        spec:
          type: NodePort
          ports:
          - port: 80
            targetPort: 80
          selector:
            app: user

    - name: manifestfiledb
      value: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: user-db
          labels:
            app: user-db
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: user-db
          template:
            metadata:
              labels:
                app: user-db
            spec:
              containers:
              - name: user-db
                image: raghadq/user-db
                ports:
                - name: mongo
                  containerPort: 27017
                volumeMounts:
                - mountPath: /tmp
                  name: tmp-volume
              volumes:
              - name: tmp-volume
                emptyDir:
                  medium: Memory
    - name: manifestfiledbsvc
      value: |
        apiVersion: v1
        kind: Service
        metadata:
          name: user-db
          labels:
            app: user-db
        spec:
          ports:
          - port: 27017
            targetPort: 27017
          selector:
            app: user-db
